### ISSUE TITLE
#M1_REP_1.4 Introduction: References and Acknowledgements

### ISSUE THREAD

**Issue by gvintng** [gvintng/INF2001_P6-1_FMS#17]
Task description:
Write up for references and acknowledges section in introduction portion for M1 report

Goals:
Complete references and acknowledges section of M1 report

Success/Completion criteria:
References and acknowledges section is fully written and proofread with no errors

Allocated time:
Submission deadline: 23/09/23 - 13 days

Start date:
10/09/23

End date:
22/09/23

Owner:
Jodie

Status of task:
Ongoing

Priority:
Low

**Comment by OWSJodie** [comment]
Work Done:

Added 2 Literature Reference :
Dohrmann, S. B., Herttua, K., & Leppin, A. (2019). Fatigue in ferry shipping employees: the role of work-family conflict and supervisor support. BMC Public Health, 19(1). https://doi.org/10.1186/s12889-019-7954-z
Bosurgi, G., Marra, S., Pellegrino, O., & Villari, M. (2020). Drivers’ workload measures to verify functionality of ferry boats boarding area. Archives of Transport. https://doi.org/10.5604/01.3001.0014.5506

Committed status:
NA

Impact on status:
Completed

Start date:
10/09/23

End Date:
22/09/23
