### ISSUE TITLE
#M1_REP_2.2 Overall Description: Product Functionality

### ISSUE THREAD

**Issue by gvintng** [gvintng/INF2001_P6-1_FMS#19]
Task description:
Write up for product functionality under overall description section for M1 report 

Goals:
Summarise major functions the product must perform or let the user perform

Success/Completion criteria:
Completion of product functionality in a bulleted list

Allocated time:
Submission deadline: 23/09/23 - 13 days

Start date:
10/09/23

End date:
22/09/23

Owner:
Wei Sheng

Status of task:
Ongoing

Priority:
High

**Comment by weisheng2200587** [comment]
Compeletd
