### ISSUE TITLE
#M1_REP_3.1 Specific Requirements: User Interface Requirements

### ISSUE THREAD

**Issue by gvintng** [gvintng/INF2001_P6-1_FMS#21]
Task description:
Write up the user interface requirements under the specific requirements section for M1 report

Goals:
To describe the logical characteristics of each interface between the software product and users to the client

Success/Completion criteria:
User interface requirements completed and satisfies client's needs

Allocated time:
Submission deadline: 23/09/23 - 13 days

Start date:
10/09/23

End date:
22/09/23

Owner:
Jun Jie

Status of task:
In-progress

Priority:
High

**Comment by JunWie** [comment]
Work Done:
Compiled a list of requirements for User Interface based on client's needs

Committed status:
NA

Impact on status:
Completed

Start date:
31/08/23
End Date:
07/09/23
