### ISSUE TITLE
#M1_REP_3.2 Specific Requirements: Functional Requirements

### ISSUE THREAD

**Issue by gvintng** [gvintng/INF2001_P6-1_FMS#22]
Task description:
Write up the functional requirements under the specific requirements section for M1 report

Goals:
To list the different product functions in detail

Success/Completion criteria:
Functional requirements completed in the report

Allocated time:
Submission deadline: 23/09/23 - 13 days

Start date:
10/09/23

End date:
22/09/23

Owner:
Jun Jie

Status of task:
In-progress

Priority:
High

**Comment by JunWie** [comment]
Work Done:
Derived a list of functional requirements based on product functionalities.

Committed Status:
NA

Impact on status:
Completed

Start date:
31/08/23
End Date:
07/08/23
