### ISSUE TITLE
#M1.3.3 Specific Requirements: Use Case Model

### ISSUE THREAD

**Issue by gvintng** [gvintng/INF2001_P6-1_FMS#23]
Task description:
Create the Use Case Diagram for our software

Goals:
Illustrate and visualize the different actors and how they interact with the system

Success/Completion criteria:
Use Case Diagram fits the software's functional requirements and added to the report

Allocated time:
Submission deadline: 23/09/23 - 13 days

Start date:
10/09/23

End date:
22/09/23

Owner:
Jun Jie

Status of task:
In-progress

Priority:
High

**Comment by JunWie** [comment]
Work Done:
Plotted Use Case diagram based on product functionality and functional requirements

Committed status:
NA

Impact on status:
Completed

Start date:
07/09/23

End Date:
08/09/23
