### ISSUE TITLE
#M1_Retrospection Individual Members

### ISSUE THREAD

**Issue by gvintng** [gvintng/INF2001_P6-1_FMS#29]
1. What went well in Milestone ONE? (What are the great things that your team is doing?)

2. What could be improved? Team dynamics, team management, task allocation and management, etc. (Are there any thing in the team that wish could be changed?)

3. What will we commit to improve in the next milestone? (Do you have ideas that could improve the current situation of your team?)

**Comment by gvintng** [comment]
What went well in Milestone ONE? (What are the great things that your team is doing?)

The team was able to work together and accomplish the tasks required despite being unclear of certain aspects of the M1 submission.

What could be improved? Team dynamics, team management, task allocation and management, etc. (Are there any thing in the team that wish could be changed?)

Team dynamics and management was not the best and there is definitely room for improvement in these aspects. I hope that through the different milestones the team will be able to communicate more.

What will we commit to improve in the next milestone? (Do you have ideas that could improve the current situation of your team?)

We will aim to improve our communication by updating each other on our progress more frequently and ask each other questions if we are unsure of anything

**Comment by weisheng2200587** [comment]
What went well in Milestone ONE? (What are the great things that your team is doing?)

Everyone is doing some part of the report and contributing to the overall report.

What could be improved? Team dynamics, team management, task allocation and management, etc. (Are there any thing in the team that wish could be changed?)

Report quality can be improved. Communication can be clearer. The issue of individual parts should be conveyed to the group early for better solutions.

What will we commit to improve in the next milestone? (Do you have ideas that could improve the current situation of your team?)
Better team management. The task deadline should be tighter.

**Comment by shadowzxxccv** [comment]
What went well in Milestone ONE? (What are the great things that your team is doing?)

Successful Collaboration: The team effectively collaborated and achieved the required tasks for Milestone One, even when facing uncertainty regarding certain submission aspects.

What could be improved? Team dynamics, team management, task allocation and management, etc. (Are there any thing in the team that wish could be changed?)

Team Cohesion: There is room for enhancing team dynamics and cooperation. Improving how team members work together and interact is essential.

Team Leadership: Enhancing team leadership and management can yield more effective results. Clearly defined roles and responsibilities will help ensure a smoother workflow.

Task Assignment and Oversight: The process of assigning and overseeing tasks could be fine-tuned. Ensuring that tasks are distributed efficiently and tracked meticulously can enhance overall progress.

What will we commit to improve in the next milestone? (Do you have ideas that could improve the current situation of your team?)

Enhanced Communication: The team is dedicated to boosting communication among its members. This involves providing frequent progress updates and fostering a culture where team members are comfortable asking questions or seeking clarification when uncertainty arises.

Role Clarity: The team will work on establishing and communicating explicit roles and responsibilities for each team member. This will promote a streamlined workflow and reduce ambiguity about individual responsibilities.

Task Management: The team will implement improved task management practices, including thorough task tracking and deadline management, to ensure a more organized and efficient workflow.

Through these improvements, the team aspires to address challenges in team dynamics and management, leading to a more cohesive and successful performance in the upcoming milestone.

**Comment by JunWie** [comment]
What went well in Milestone ONE? (What are the great things that your team is doing?)

Each team member made a proportional contribution to the workload.

What could be improved? Team dynamics, team management, task allocation and management, etc. (Are there any thing in the team that wish could be changed?)

There wasn't much interaction with the client to identify their need, and no follow-up was done. There is a need to redo use cases multiple times due to confusion and previous tasks requirements.

For the upcoming milestone, we will be committed to taking more initiative and reduce the tendency of doing tasks alone.

**Comment by OWSJodie** [comment]
What went well in Milestone ONE? (What are the great things that your team is doing?)

I'm not too sure..

What could be improved? Team dynamics, team management, task allocation and management, etc. (Are there any thing in the team that wish could be changed?)

We didn't have a clear leader, and most the time we wait for one another, til the last min, I think we can improve from team management prospects, even once we have a clear leader, our team communication was quite bad.

What will we commit to improve in the next milestone? (Do you have ideas that could improve the current situation of your team?)

I believe we can improve from by accepting the task and being automatic to communicate to see where require help and tries to seek for clear answer by discussing the group
