### ISSUE TITLE
#M2.2.1 Sequence Diagram: Use Case 2

### ISSUE THREAD

**Issue by gvintng** [gvintng/INF2001_P6-1_FMS#36]
Task description:
Create sequence diagram based on UC2: View Job Assignment

Goals:
To develop a sequence diagram that illustrates the workflow of staff accessing and viewing their weekly job assignments

Success/Completion criteria:
UC2 sequence diagram completed

Allocated time:
21 days

Start date:
5 Oct 2023

End date:
26 Oct 2023

Owner:
Wei Sheng

Status of task:
In-progress

Priority:
High

**Comment by weisheng2200587** [comment]
Work Done:
The sequence Diagram has been checked through and put together 

Committed status:
NA

Impact on status:
NA

Impact on deadline?
NA

Start date:
12 Oct 2023

End Date:
29 Oct 2023
