### ISSUE TITLE
#M2.2.2 Sequence Diagram: Use Case 8

### ISSUE THREAD

**Issue by gvintng** [gvintng/INF2001_P6-1_FMS#37]
Task description:
Create sequence diagram based on UC8: Allocate Jobs to Staff

Goals:
To develop a sequence diagram that illustrates the workflow of allocating jobs to staff in the system

Success/Completion criteria:
UC7 sequence diagram completed

Allocated time:
21 days

Start date:
5 Oct 2023

End date:
26 Oct 2023

Owner:
Jodie,

Status of task:
In-progress

Priority:
High

**Comment by OWSJodie** [comment]
Work Done:
Sequence Diagram: Use Case 8 completed.

Committed status:
NA

Impact on status:
Complete

Impact on deadline?
NA

Start date:
5 Oct 2023

End date:
26 Oct 2023
