### ISSUE TITLE
#M2.3 Component Diagram

### ISSUE THREAD

**Issue by gvintng** [gvintng/INF2001_P6-1_FMS#38]
Task description:
Identify components and design component diagram

Goals:
Create a component diagram based on class diagram

Success/Completion criteria:
Component diagram completed

Allocated time:
14 days

Start date:
12 Oct 2023

End date:
26 Oct 2023

Owner:
Jun Jie, Wei Sheng, Jodie

Status of task:
In-progress

Priority:
High

**Comment by JunWie** [comment]
Work done:
Identified the components in a component diagram
Created a component diagram based on the class diagram

Committed status:
NA

Impact on status:
Completed

Start date:
12 Oct 2023

End Date:
26 Oct 2023
