### ISSUE TITLE
#M2.4.2 Changes in Safety and Security Requirements

### ISSUE THREAD

**Issue by gvintng** [gvintng/INF2001_P6-1_FMS#41]
Task description:
Review feedback given for safety and security requirements given in M1 report and make changes accordingly

Goals:
To review and make changes to safety and security requirements in M2 report based on feedback

Success/Completion criteria:
Safety and security requirements updated in M2

Allocated time:
10 days

Start date:
16 Oct 2023

End date:
26 Oct 2023

Owner:
Gavin

Status of task:
In-progress

Priority:
High

**Comment by OWSJodie** [comment]
Work Done:
Rewritten the SSR in third person view and fit the 7 good traits of requirements.

Committed status:
NA

Impact on status:
Completed on time

Start date:
17 Oct 2023

End Date:
26 Oct 2023
