### ISSUE TITLE
#M2.4.3 Revise Use Case Descriptions

### ISSUE THREAD

**Issue by gvintng** [gvintng/INF2001_P6-1_FMS#42]
Task description:
Review feedback given for use case descriptions given in M1 report and make changes accordingly

Goals:
To review and make changes to use case descriptions in M2 report based on feedback

Success/Completion criteria:
Use case descriptions updated in M2

Allocated time:
10 days

Start date:
16 Oct 2023

End date:
26 Oct 2023

Owner:
Jodie

Status of task:
In-progress

Priority:
High

**Comment by weisheng2200587** [comment]
Work done:
Reviewed all use case descriptions of M1. 
Refer to the feedback given and make changes to our use case descriptions.


Committed status:
NA

Impact on status:
Completed

Start date:
12 Oct 2023

End Date:
28 Oct 2023
