### ISSUE TITLE
#M2.4.4 Updated Use Case Diagram

### ISSUE THREAD

**Issue by gvintng** [gvintng/INF2001_P6-1_FMS#43]
Task description:
Revise and update use case diagram based on changes made to use case description

Goals:
To revise the use case diagram to reflect changes made to use case descriptions based on feedback in M1

Success/Completion criteria:
Use case diagram updated

Allocated time:
10 days

Start date:
16 Oct 2023

End date:
26 Oct 2023

Owner:
Jun Jie

Status of task:
In-progress

Priority:
High

**Comment by JunWie** [comment]
Removed certain use case descriptions as some use case are too generic
Revamp of the use case desciptions
Create a new use case diagram after feedback in M1

Committed status:
NA
Impact on status:
Completed

Start date:
16 Oct 2023

End Date:
26 Oct 2023
