### ISSUE TITLE
#M2.5 Final M2 Review and Approval

### ISSUE THREAD

**Issue by gvintng** [gvintng/INF2001_P6-1_FMS#48]
Task description:
Do a final review of the M2 report and prepare for submission

Goals:
To check and do a final review of the M2 report and make sure its ready for submission

Success/Completion criteria:
M2 report finalized and approved by group leader

Allocated time:
2 days

Start date:
26 Oct 2023

End date:
27 Oct 2023

Owner:
Jodie

Status of task:
In-progress

Priority:
High

**Comment by OWSJodie** [comment]
Work Done:
Finalized the report and details, cross check with the team for validation.

Committed status:
NA

Impact on status:
Completed on time

Start date:
26 Oct 2023

End Date:
27 Oct 2023
