### ISSUE TITLE
3.1 Prototyping

### ISSUE THREAD

**Issue by gvintng** [gvintng/INF2001_P6-1_FMS#49]
Task description:
Identify and write up on the software architecture patterns and detailed design for the FMS.
Draft out a user interface for the system and review it

Goals:
- Identified the software architecture pattern that will be used for the FMS
- Identified the detailed design patterns that will be used for the FMS 
- Produce a draft of how the user interface will look like
- Review the usability of the user interface and ensure it meets the functional and non-functional requirements of the FMS

Success/Completion criteria:
- Write up for software architecture pattern completed
- Write up for detailed design patterns completed
- User interface draft produced
- User interface design completed and approved

Allocated time:
24 days

Start date:
30 Oct 2023

End date:
23 Nov 2023

Owner:
All

Status of task:
In-progress

Priority:
High

**Comment by weisheng2200587** [comment]
Figma prototype is completed. Report writing needed

**Comment by weisheng2200587** [comment]
The report is complete. Prove reading before submission
