### ISSUE TITLE
#M1_REP_1.1 Introduction: Product Scope

### ISSUE THREAD

**Issue by gvintng** [gvintng/INF2001_P6-1_FMS#5]
Task description:
Write up for product scope section in introduction portion for M1 report

Goals:
Provide a short description of the software scope, boundaries and its purpose

Success/Completion criteria:
Completion of product scope including benefits, objectives and goals

Allocated time:
Submission deadline: 23/09/23 - 13 days

Start date:
10/09/23

End date:
22/09/23

Owner:
Jodie

Status of task:
Ongoing

Priority:
Medium

**Comment by OWSJodie** [comment]
Work Done:
Understanding the job scopes from the initial requirement provided

Provided a brief description of the product scope.

Committed status:
NA

Impact on status:
Completed

Start date:
10/09/23

End Date:
22/09/23
