### ISSUE TITLE
3.1.1 Review Software Architecture Pattern

### ISSUE THREAD

**Issue by gvintng** [gvintng/INF2001_P6-1_FMS#50]
Task description:
Identify and write up on the software architecture patterns  for the FMS.

Goals:
- Identified the software architecture pattern that will be used for the FMS
- Write up for rationale and description of the chosen architecture pattern

Success/Completion criteria:
- Write up completed

Allocated time:
24 days

Start date:
30 Oct 2023

End date:
23 Nov 2023

Owner:
Gavin

Status of task:
In-progress

Priority:
Medium

**Comment by weisheng2200587** [comment]
Reviewed and proof read of software architecture pattern
