### ISSUE TITLE
3.1.3 User Interface and wireframe Draft

### ISSUE THREAD

**Issue by gvintng** [gvintng/INF2001_P6-1_FMS#52]
Task description:
Draft out a user interface for the system

Goals:
- Produce a draft of how the user interface will look like

Success/Completion criteria:
- User interface draft produced

Allocated time:
24 days

Start date:
30 Oct 2023

End date:
23 Nov 2023

Owner:
Wei Sheng
Jun Jie

Status of task:
In-progress

Priority:
High

**Comment by weisheng2200587** [comment]
Figma of user interface is completed. Checking of any error and flaws
