### ISSUE TITLE
3.1.4 Review User Interface Design

### ISSUE THREAD

**Issue by gvintng** [gvintng/INF2001_P6-1_FMS#53]
Task description:
Review design for user interface

Goals:
- Review the usability of the user interface and ensure it meets the functional and non-functional requirements of the FMS

Success/Completion criteria:
- User interface design completed and approved

Allocated time:
24 days

Start date:
30 Oct 2023

End date:
23 Nov 2023

Owner:
Jodie

Status of task:
In-progress

Priority:
High

**Comment by OWSJodie** [comment]
Work Done:
Reviewing  user interface and it meets the user requirements 

Committed status:
None

Impact on status:
Completed

Start date:
30 Oct 2023

End Date:
23 Nov 2023
