### ISSUE TITLE
3.3 Black-box Testing

### ISSUE THREAD

**Issue by gvintng** [gvintng/INF2001_P6-1_FMS#55]
Task description:
Implement black-box testing for UC13 - Add New User

Goals:
- Produce decision table and test cases

Success/Completion criteria:
- Decision and test case tables completed

Allocated time:
24 days

Start date:
30 Oct 2023

End date:
23 Nov 2023

Owner:
Jodie

Status of task:
In-progress

Priority:
High

**Comment by weisheng2200587** [comment]
Prove reading of black box testing done and ready for submission

**Comment by OWSJodie** [comment]
Work Done:
Chosen UC 13 , Createnewuser() method, complete blackbox testing 

Committed status:
None

Impact on status:
Completed

Start date:
30 Oct 2023

End Date:
23 Nov 2023
