### ISSUE TITLE
3.4 Whitebox Testing

### ISSUE THREAD

**Issue by gvintng** [gvintng/INF2001_P6-1_FMS#56]
Task description:
Identify prominent method and implement white-box testing

Goals:
- Identify prominent method to do white-box testing

Success/Completion criteria:
- Construct CFG
- Calculate cyclomatic complexity
- Calculate basis paths

Allocated time:
24 days

Start date:
30 Oct 2023

End date:
23 Nov 2023

Owner:
Jodie

Status of task:
In-progress

Priority:
High

**Comment by OWSJodie** [comment]
Work Done:
completed whitebox testing

Committed status:
None

Impact on status:
Completed

Start date:
30 Oct 2023

End Date:
23 Nov 2023
